### ISSUE TITLE
Sanity check against icosphere or similar

### ISSUE THREAD

**Issue by gomezzz** [rasmusmarak/67P-Swarm#13]
Check acceleration and trajectory produced with icosphere or similar mesh and maybe density to emulate some nice point source. Check against keplerian solution (optionally manually)

**Comment by rasmusmarak** [comment]
Here's a link to the presentation from our weekly catchup 7/2-23 (including som results from the sanity check): 
https://docs.google.com/presentation/d/1PmHLs8Ir1L829seUmRu0iqCVXHwkDmjKCVJI_zkYbVc/edit?usp=sharing

**Comment by rasmusmarak** [comment]
Next to do: Keplerian comparison, run a few points in different angles to see the change in magnitude of error

**Comment by gomezzz** [comment]
> Next to do: Keplerian comparison, run a few points in different angles to see the change in magnitude of error

Another trick you could use is scale the mesh down by a large factor but increase its density accordingly. Then it should really be a point-source and give you virtually keplerian dynamics?
